# Generated by Django 5.0.1 on 2024-02-07 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('tipo_producto', models.CharField(max_length=255, verbose_name='Tipo de producto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('carnet_id', models.CharField(max_length=11, unique=True, verbose_name='Carnet de Identidad')),
                ('numero_telefono', models.CharField(max_length=8, verbose_name='Número de telefóno')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mi_negocioApp.producto')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
